/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BranchingSpheresCanvas: typeof import('./components/BranchingSpheresCanvas.vue')['default']
    BranchingUpward2Canvas: typeof import('./components/BranchingUpward2Canvas.vue')['default']
    BranchingUpwardCanvas: typeof import('./components/BranchingUpwardCanvas.vue')['default']
    CanvasInitOverlay: typeof import('./components/CanvasInitOverlay.vue')['default']
    CanvasToolbar: typeof import('./components/CanvasToolbar.vue')['default']
    EllipticalTestCanvas: typeof import('./components/ellipticalTestCanvas.vue')['default']
    FunShapesCanvas: typeof import('./components/funShapesCanvas.vue')['default']
    GridBlowingInWind: typeof import('./components/gridBlowingInWind.vue')['default']
    InitializationInputs: typeof import('./components/initializationInputs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartPaintTesting1Canvas: typeof import('./components/SmartPaintTesting1Canvas.vue')['default']
    SphereEmissionCanvas: typeof import('./components/SphereEmissionCanvas.vue')['default']
    SpringGridsCanvas: typeof import('./components/SpringGridsCanvas.vue')['default']
    ToolbarNumericInput: typeof import('./components/ToolbarNumericInput.vue')['default']
  }
}
