/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComputationalCanvas: typeof import('./components/computationalCanvas.vue')['default']
    EllipticalTestCanvas: typeof import('./components/ellipticalTestCanvas.vue')['default']
    FunShapesCanvas: typeof import('./components/funShapesCanvas.vue')['default']
    GridBlowingInWind: typeof import('./components/gridBlowingInWind.vue')['default']
    InitializationInputs: typeof import('./components/initializationInputs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WindParticlesCanvas: typeof import('./components/WindParticlesCanvas.vue')['default']
  }
}
